# Site Build Settings

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "COVIDoutlook.info"
description:	       "Original data-driven analyses and projections of the COVID-19 crisis in the United States"
author:              "The COVIDoutlook Team"

twitter:
  username: COVIDoutlook
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: https://www.covidoutlook.info/assets/img/hlogo-blackonwhite.png

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml
